---
# tasks for consul
- include: ./validate.yml

- name: consul user
  user: name=consul
  tags:
    - consul
    - consul.user

- name: consul group
  group: name=consul
  tags:
    - consul
    - consul.group

- name: download consul binary
  get_url: url=https://releases.hashicorp.com/consul/{{ version }}/consul_{{ version }}_linux_amd64.zip
  args:
    force: true
    dest: /tmp
    mode: 0644
    sha256sum: "{{ sha256sum[version] }}"
  tags:
    - consul
    - consul.download

#- get_url: url=https://dl.bintray.com/mitchellh/consul/{{ version }}_web_ui.zip
#  args: ... for WebUI
#

- name: install unzip
  yum: name=unzip
  tags:
    - consul
    - consul.yum

- name: unarchive
  unarchive: src={{ tmp_dir }}/consul_{{ version }}_linux_amd64.zip dest={{ install_dir }} copy=no
  tags:
    - consul
    - consul.unarchive

- name: make it executable
  file: path={{ install_dir }}/consul owner=consul group=consul mode=0755 state=file
  tags:
    - consul
    - consul.chmod

- name: make directories
  file: path={{ item }} owner=consul group=consul mode=0755 state=directory
  with_items:
    - "{{ config_dir }}"
    - "{{ data_dir }}"
  tags:
    - consul
    - consul.dirs

- name: init-script
  copy: src=./init-script dest=/etc/init.d/consul owner=consul group=consul mode=0755
  when: ansible_distribution_major_version in ["6"]
  tags:
    - consul
    - consul.init-script

- name: sysconfig file
  template: src=./sysconfig dest=/etc/sysconfig/consul owner=consul group=consul mode=0644
  when: ansible_distribution_major_version in ["6", "7"]
  tags:
    - consul
    - consul.conf

- name: consul.service file
  copy: src=./consul.service dest=/etc/systemd/system/consul.service owner=consul group=consul mode=0644
  when: ansible_distribution_major_version in ["7"]
  tags:
    - consul
    - consul.conf

- name: config file
  template: src=./consul.json dest={{ config_dir }}/consul.json owner=consul group=consul mode=0644
  notify:
    - reload consul
  tags:
    - consul
    - consul.json

- name: init.d/consul-leave
  template: src=./consul-leave dest=/etc/init.d/consul-leave owner=consul group=consul mode=0755
  when: ansible_distribution_major_version in ["6", "7"]
  tags:
    - consul
    - consul.rc.d

- name: link to rc.d
  file: src=/etc/init.d/consul-leave path=/etc/rc{{ item }}.d/K10consul-leave state=link owner=consul group=consul
  with_items:
    - "0"  # shutdown
    - "6"  # reboot
  when: ansible_distribution_major_version in ["6", "7"]
  tags:
    - consul
    - consul.rc.d

- name: service
  service: name=consul state=started enabled=yes
  tags:
    - consul
    - consul.service
